#!/bin/bash
# Render.com Manual Configuration Script
# If render.yaml isn't working, use this guide to manually configure the service

echo "========================================"
echo "Render Manual Configuration Guide"
echo "========================================"
echo ""
echo "The issue: Render is running 'gunicorn app:app' instead of 'gunicorn Logistics.wsgi:application'"
echo ""
echo "SOLUTION: Delete the current service and recreate it"
echo ""
echo "Step 1: Delete Current Service"
echo "  1. Go to https://dashboard.render.com"
echo "  2. Click on 'pulsetrack-backend' service"
echo "  3. Scroll to bottom and click 'Delete Service'"
echo "  4. Type the service name to confirm"
echo ""
echo "Step 2: Create New Service with render.yaml"
echo "  1. Go to https://render.com"
echo "  2. Click 'New +' button"
echo "  3. Select 'Web Service'"
echo "  4. Connect your GitHub repository"
echo "  5. IMPORTANT: Look for option to use 'render.yaml'"
echo "              or select 'Existing Render Config'"
echo "  6. Click 'Create Web Service'"
echo ""
echo "Step 3: Verify Configuration in Dashboard"
echo "  1. After service is created, go to Settings tab"
echo "  2. Under 'Build Command' should show:"
echo "     pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
echo "  3. Under 'Start Command' should show:"
echo "     bash -c 'gunicorn Logistics.wsgi:application ...'"
echo "  4. If not, manually edit these fields"
echo ""
echo "Step 4: Deployment"
echo "  1. Wait for build to complete"
echo "  2. Check Logs tab for any errors"
echo "  3. Once deployment shows green checkmark, service is live"
echo ""
echo "========================================"
echo "MANUAL SETTINGS (if render.yaml doesn't work):"
echo "========================================"
echo ""
echo "Build Command:"
echo "  pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && python manage.py collectstatic --noinput"
echo ""
echo "Start Command:"
echo "  gunicorn Logistics.wsgi:application --bind 0.0.0.0:\$PORT --workers 2 --worker-class sync --timeout 60 --log-level info"
echo ""
echo "Environment Variables:"
echo "  DEBUG = false"
echo "  SECRET_KEY = (let Render generate)"
echo "  ALLOWED_HOSTS = *.render.com,localhost,127.0.0.1"
echo "  CORS_ALLOWED_ORIGINS = https://pulsetrack-frontend-henna.vercel.app,https://*.render.com"
echo "  DATABASE_URL = (link to PostgreSQL database service)"
echo ""
